### ISSUE TITLE
Use tabular numbers to keep the clock from moving around

### ISSUE THREAD

**Issue by cassidyjames** [candiedoperation/ordne#13]
![Ordne Logo](https://raw.githubusercontent.com/candiedoperation/ordne/master/data/icons/64.svg) 
# Issue
Pango (the text renderer) and Inter (the default elementary OS font) have a nice feature that lets you use tabular numbers, so the clock won't move around (the numbers and their spacing are all adjusted to be the same width). It'd be nice to throw that on the clock. :)
## Suggested Actions
 - You can see where we added this to the clock in elementary OS itself: https://github.com/elementary/wingpanel-indicator-datetime/pull/246/files

**Comment by candiedoperation** [comment]
Sure, Trying to Implement it to the app...

**Comment by candiedoperation** [comment]
I've updated the source. BTW, I have added a pull request to https://github.com/elementary/appcenter-reviews but now, I've changed the source. What do I need to do to update to the reviewer?

**Comment by candiedoperation** [comment]
👍️ I've modified the source code...
Thank You for contributing to this issue
