### ISSUE TITLE
Flatpak: App Fails to Load `canberra-gtk-module`

### ISSUE THREAD

**Issue by candiedoperation** [candiedoperation/ordne#17]
![Ordne Logo](https://raw.githubusercontent.com/candiedoperation/ordne/master/data/icons/64.svg) 
# Issue
`Gtk-Message: 11:00:02.595: Failed to load module "canberra-gtk-module"`
Despite Adding `libcanberra` to the flatpak `.yml` as a dependency and `- '--socket=pulseaudio'` to `finish-args:`, it fails to load during runtime which prevent the app from beeping on countdown end.
## Suggested Fix
_No Suggestions yet_

**Comment by candiedoperation** [comment]
Tip for Fixing the issue at https://github.com/elementary/appcenter-reviews/pull/27#issuecomment-887678513

**Comment by ryonakano** [comment]
The message `Failed to load module "canberra-gtk-module"` is shown in any flatpaked apps that does not use libcanberra, so this should not be a problem.

Also, as far as I test your app, the sound at the end of the timer is played in my end.

**Comment by candiedoperation** [comment]
> The message `Failed to load module "canberra-gtk-module"` is shown in any flatpaked apps that does not use libcanberra, so this should not be a problem.
> 
> Also, as far as I test your app, the sound at the end of the timer is played in my end.

Thank You @ryonakano. I'll Be closing the issue then
